# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-26 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_musician'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Musician',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp', '-updated']},
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Django_images'),
        ),
    ]
