# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-31 14:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20170731_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='puplish',
            new_name='publish',
        ),
    ]
